highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Renan Netto's Resume
name: Renan Netto
email: renan.o.netto@gmail.com
email_full: mailto:renan.o.netto@gmail.com
website: renannetto.me
website_full: http://renannetto.me
github: renannetto
tel: +55 48 99170481
tel_full: tel:+554899170481
google_maps: 'https://www.google.com.br/maps/place/Departamento+de+Inform%C3%A1tica+e+Estat%C3%ADstica/@-27.6005034,-48.5191306,17z/data=!4m6!1m3!3m2!1s0x952739ab06a8bca7:0x9904bca1385e0f9d!2sUniversidade+Federal+de+Santa+Catarina!3m1!1s0x0000000000000000:0xc2fd35f96d3fb9b3?hl=pt-BR'
address: Campus Universitário S/N
postcode: 88040-900
city: Florianópolis
country: Brazil
google_analytics: UA-70935330-1

# needed for travis-ci build
exclude: [vendor]
